### ISSUE TITLE
No deltatime

### ISSUE THREAD

**Issue by Familex** [d-002/hardest#1]
It seems that the game speed is highly dependent on the processor speed.
This makes the game impossible on weak computers.
I think this can be fixed by using deltatime in player movement.

**Comment by d-002** [comment]
Hi,
I remember I did not want to add a deltatime because acceleration would need to be changed a lot, to account for the different possible framerates. I will however add a deltatime and try to make the movement be the same on all framerates. Thank you for pointing this out.

**Comment by d-002** [comment]
Hello again
[This commit](https://github.com/d-002/hardest/commit/78142fd4a3a9a70b94c0a930a8cb1f3b35a710f0) should have fixed the issue. Please comment again if you have any issues with the new physics, your help is greatly appreciated!
There is no deltatime in the level editor for now.
